package nu.ac.th.rescueunit;

public class RescueState {
	public static final int ABANDON = -100;
	public static final int REJECT = -1;
	public static final int PENDING = 0;
	public static final int ACCEPT = 1;
	public static final int COMPLETE = 100;
	
	public static final String DEFAULT_MESSAGE = "State Generated By System";
}
